//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veteriner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VeterinerDbEntities : DbContext
    {
        public VeterinerDbEntities()
            : base("name=VeterinerDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Custormers> Custormers { get; set; }
        public virtual DbSet<Pets> Pets { get; set; }
        public virtual DbSet<prescriptions> prescriptions { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vaccinations> vaccinations { get; set; }
        public virtual DbSet<visits> visits { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
    }
}
