//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veteriner
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescriptions
    {
        public int Id { get; set; }
        public Nullable<int> visit_id { get; set; }
        public string medicine_name { get; set; }
        public string dosage { get; set; }
        public string duration { get; set; }
        public string instructions { get; set; }
    
        public virtual visits visits { get; set; }
    }
}
