//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veteriner
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaccinations
    {
        public int Id { get; set; }
        public Nullable<int> pet_id { get; set; }
        public string vaccine_name { get; set; }
        public Nullable<System.DateTime> vaccination_date { get; set; }
        public Nullable<System.DateTime> next_due_date { get; set; }
        public string notes { get; set; }
    
        public virtual Pets Pets { get; set; }
    }
}
