//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veteriner
{
    using System;
    using System.Collections.Generic;
    
    public partial class visits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visits()
        {
            this.prescriptions = new HashSet<prescriptions>();
        }
    
        public int Id { get; set; }
        public Nullable<int> pet_id { get; set; }
        public Nullable<System.DateTime> visit_date { get; set; }
        public string reason { get; set; }
        public string diagnosis { get; set; }
        public string treatment { get; set; }
        public string notes { get; set; }
    
        public virtual Pets Pets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prescriptions> prescriptions { get; set; }
    }
}
